### ISSUE TITLE
[UI] 내역 등록 화면 레이아웃 

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-accountbook-16#30]
## Screen Type
- 내역 등록

## Description
- 기본 레이아웃

## Task
- [x] 날짜 선택 다이얼로그
- [x] 드롭다운 컴포넌트 구현
- [x] 기본 레이아웃 구현
