### ISSUE TITLE
[FEAT] 결제수단, 카테고리 등록/수정 기능 구현

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-accountbook-16#37]
## Screen Type
- 설정 등록화면

## Description
- 결제수단, 카테고리 등록 및 수정 기능 구현

## Task
- [x] id로 선택된 데이터 불러오기
- [x] id가 없는 경우 추가 하는 것으로 간주
- [x] 등록/수정 기능 구현
