### ISSUE TITLE
[FEAT] 롱클릭 삭제 기능 구현

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-accountbook-16#41]
## Screen Type
- 내역화면

## Description
- 리스트 아이템 길게 눌러 선택모드 진입 후 원하는 아이템을 선택해 삭제

## Task
- [x] 리스트 아이템 롱클릭 이벤트 처리
- [x] 삭제 버튼 눌러 선택된 아이템 전체 삭제
- [x] 선택모드 진입 시 필터 비활성화
