### ISSUE TITLE
[UI] 내역화면 기본 레이아웃

### ISSUE THREAD

**Issue by oreocube** [woowa-techcamp-2022/android-accountbook-16#8]
## Screen Type
- 내역화면

## Description
- 내역화면 기본 레이아웃

## Task
- [x] 카테고리 태그 컴포넌트로 분리
- [x] 앱바 컴포넌트 구현
- [x] 더미 데이터 생성
- [x] 리스트 레이아웃 구현
